### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by timemaster5** [tinyusbboard/hid-KeyboardMouse#1]
Hi, I would like to try your arduino library, but unfortunatelly I cannot get working version. You probably have v-usb directory inside gcc-code but this one is not a part of git tree.. Could you provide full package for arduino software without links ?

Thanks

**Comment by tinyusbboard** [comment]
Hi.
At the moment there is no great strategy to implement all the libraries needed for compiling.
So the current situation is to clone all repositories of tinyusbboard into the same basedir.
Then all the links should be correct.
If you still experience trouble I will provide you a zip-file.

BR Stephan

**Comment by timemaster5** [comment]
Ok, got it.. and sorry I finally found that clue in your account description. Maybe this should be in README ? anyway, I was looking for V-USB HID Keyboard and Mouse usable in my arduino project. This one looks fine and is somehow similar to https://github.com/adafruit/Adafruit-Trinket-USB/tree/master/TrinketHidCombo .. So if you wan't here you can get something interesting too for your project. I finally took the trinket one, because is much closer to my project based on atmega 168. Anyway, thank you for interesting work.
